server:
  port: 9091
spring:
  batch:
    jdbc:
      initialize-schema: always
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: ENC(7R4PqEBAJrbcY0w5QUli1xwGmnKjbjwFUtW8NiIaN0JiLNLss5aGEVCWoXmLHNm2tJhDOZ/HRcaEMe2q7jzzkH7reRHlqc/pJ7+MyO5JVEEJqN0MTa8afHAy94K7px2eSVwSrWgwDYHHUVh8R+/0tgUjVZjl2+N5)
      username: ENC(2B3sO2/zU7tj2IXe2co+Ag==)
      password: ENC(2B3sO2/zU7tj2IXe2co+Ag==)
      maximum-pool-size: 80
      max-lifetime: 1800000
  h2:
    console:
      enabled: true
  jpa:
    database: MYSQL
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        logging.level:
        org.hibernate.SQL: debug

  sql:
    init:
      mode: always
      continue-on-error: false # 서버 시작시 sql문을 실행할 때 오류 무시하고 계속 진행
      encoding: UTF-8
      separator: ; # sql문을 구분할 구분자

  quartz:
    job-store-type: jdbc # jobStore를 jdbc로 사용 (기본 사용시 메모리 사용)
    jdbc:
      initialize-schema: always # 항상 쿼츠 관련 테이블을 drop 후 생성한다.

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
